---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcadectl-destroy-controller
  namespace: arcadectl-system
  labels:
    app.kubernetes.io/name: arcadectl-destroy-controller
    app.kubernetes.io/part-of: arcadectl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcadectl-destroy-admin
  namespace: arcadectl-system
  labels:
    app.kubernetes.io/name: arcadectl-destroy-admin
    app.kubernetes.io/part-of: arcadectl
automountServiceAccountToken: false
