---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arcadectl-destroy-volumeattachment-reader
  labels:
    app.kubernetes.io/name: arcadectl-destroy-controller
    app.kubernetes.io/part-of: arcadectl
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch"]
