---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: arcadectl-restore-candidate-pvc-create
  labels:
    app.kubernetes.io/name: arcadectl-controller
    app.kubernetes.io/part-of: arcadectl
spec:
  policyName: arcadectl-restore-candidate-pvc-create
  validationActions:
    - Deny
  matchResources:
    matchPolicy: Equivalent
    objectSelector: {}
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: arcadectl-system
