---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcadectl-controller
  namespace: arcadectl-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcade.gobha.me
  resources:
  - arcadeoperations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcade.gobha.me
  resources:
  - arcadeoperations/status
  - gamebackups/status
  - gamerestores/status
  - gameservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcade.gobha.me
  resources:
  - gamebackups
  - gamerestores
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcade.gobha.me
  resources:
  - gamedestroys
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - arcade.gobha.me
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - watch
