//go:build !ignore_autogenerated

// Copyright 2026 gobha-me
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcadeOperation) DeepCopyInto(out *ArcadeOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcadeOperation.
func (in *ArcadeOperation) DeepCopy() *ArcadeOperation {
	if in == nil {
		return nil
	}
	out := new(ArcadeOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcadeOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcadeOperationList) DeepCopyInto(out *ArcadeOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArcadeOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcadeOperationList.
func (in *ArcadeOperationList) DeepCopy() *ArcadeOperationList {
	if in == nil {
		return nil
	}
	out := new(ArcadeOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArcadeOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcadeOperationSpec) DeepCopyInto(out *ArcadeOperationSpec) {
	*out = *in
	in.Admission.DeepCopyInto(&out.Admission)
	in.Request.DeepCopyInto(&out.Request)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcadeOperationSpec.
func (in *ArcadeOperationSpec) DeepCopy() *ArcadeOperationSpec {
	if in == nil {
		return nil
	}
	out := new(ArcadeOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArcadeOperationStatus) DeepCopyInto(out *ArcadeOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(OperationPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Child != nil {
		in, out := &in.Child, &out.Child
		*out = new(OperationChildReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]OperationServerTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RetainedWorld != nil {
		in, out := &in.RetainedWorld, &out.RetainedWorld
		*out = new(OperationRetainedWorld)
		(*in).DeepCopyInto(*out)
	}
	if in.DestroyPreview != nil {
		in, out := &in.DestroyPreview, &out.DestroyPreview
		*out = new(GameDestroyPreview)
		(*in).DeepCopyInto(*out)
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = new(OperationFailure)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArcadeOperationStatus.
func (in *ArcadeOperationStatus) DeepCopy() *ArcadeOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ArcadeOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactProvenance) DeepCopyInto(out *ArtifactProvenance) {
	*out = *in
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	in.RepositorySecretRef.DeepCopyInto(&out.RepositorySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactProvenance.
func (in *ArtifactProvenance) DeepCopy() *ArtifactProvenance {
	if in == nil {
		return nil
	}
	out := new(ArtifactProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactVerification) DeepCopyInto(out *ArtifactVerification) {
	*out = *in
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactVerification.
func (in *ArtifactVerification) DeepCopy() *ArtifactVerification {
	if in == nil {
		return nil
	}
	out := new(ArtifactVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupArtifact) DeepCopyInto(out *BackupArtifact) {
	*out = *in
	in.Provenance.DeepCopyInto(&out.Provenance)
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	in.Verification.DeepCopyInto(&out.Verification)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupArtifact.
func (in *BackupArtifact) DeepCopy() *BackupArtifact {
	if in == nil {
		return nil
	}
	out := new(BackupArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CandidateDataVerification) DeepCopyInto(out *CandidateDataVerification) {
	*out = *in
	in.VerifiedAt.DeepCopyInto(&out.VerifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CandidateDataVerification.
func (in *CandidateDataVerification) DeepCopy() *CandidateDataVerification {
	if in == nil {
		return nil
	}
	out := new(CandidateDataVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdDataFence) DeepCopyInto(out *ColdDataFence) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	in.EstablishedAt.DeepCopyInto(&out.EstablishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdDataFence.
func (in *ColdDataFence) DeepCopy() *ColdDataFence {
	if in == nil {
		return nil
	}
	out := new(ColdDataFence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSpec) DeepCopyInto(out *ComputeSpec) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSpec.
func (in *ComputeSpec) DeepCopy() *ComputeSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataOperationRequest) DeepCopyInto(out *DataOperationRequest) {
	*out = *in
	if in.InlineCredentials != nil {
		in, out := &in.InlineCredentials, &out.InlineCredentials
		*out = new(InlineCredentials)
		**out = **in
	}
	in.RepositorySecretRef.DeepCopyInto(&out.RepositorySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataOperationRequest.
func (in *DataOperationRequest) DeepCopy() *DataOperationRequest {
	if in == nil {
		return nil
	}
	out := new(DataOperationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataOperationStatus) DeepCopyInto(out *DataOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(DataSourceSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Fence != nil {
		in, out := &in.Fence, &out.Fence
		*out = new(ColdDataFence)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(BackupArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeDisposition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataOperationStatus.
func (in *DataOperationStatus) DeepCopy() *DataOperationStatus {
	if in == nil {
		return nil
	}
	out := new(DataOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPathIdentity) DeepCopyInto(out *DataPathIdentity) {
	*out = *in
	in.ClaimRef.DeepCopyInto(&out.ClaimRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPathIdentity.
func (in *DataPathIdentity) DeepCopy() *DataPathIdentity {
	if in == nil {
		return nil
	}
	out := new(DataPathIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSnapshot) DeepCopyInto(out *DataSourceSnapshot) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSnapshot.
func (in *DataSourceSnapshot) DeepCopy() *DataSourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(DataSourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactGameServerReference) DeepCopyInto(out *ExactGameServerReference) {
	*out = *in
	in.ExactLocalReference.DeepCopyInto(&out.ExactLocalReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactGameServerReference.
func (in *ExactGameServerReference) DeepCopy() *ExactGameServerReference {
	if in == nil {
		return nil
	}
	out := new(ExactGameServerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactLocalReference) DeepCopyInto(out *ExactLocalReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactLocalReference.
func (in *ExactLocalReference) DeepCopy() *ExactLocalReference {
	if in == nil {
		return nil
	}
	out := new(ExactLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactSecretReference) DeepCopyInto(out *ExactSecretReference) {
	*out = *in
	in.ExactLocalReference.DeepCopyInto(&out.ExactLocalReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactSecretReference.
func (in *ExactSecretReference) DeepCopy() *ExactSecretReference {
	if in == nil {
		return nil
	}
	out := new(ExactSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackup) DeepCopyInto(out *GameBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackup.
func (in *GameBackup) DeepCopy() *GameBackup {
	if in == nil {
		return nil
	}
	out := new(GameBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupList) DeepCopyInto(out *GameBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupList.
func (in *GameBackupList) DeepCopy() *GameBackupList {
	if in == nil {
		return nil
	}
	out := new(GameBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupSpec) DeepCopyInto(out *GameBackupSpec) {
	*out = *in
	in.DataOperationRequest.DeepCopyInto(&out.DataOperationRequest)
	in.Source.DeepCopyInto(&out.Source)
	if in.SourceData != nil {
		in, out := &in.SourceData, &out.SourceData
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupSpec.
func (in *GameBackupSpec) DeepCopy() *GameBackupSpec {
	if in == nil {
		return nil
	}
	out := new(GameBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupStatus) DeepCopyInto(out *GameBackupStatus) {
	*out = *in
	in.DataOperationStatus.DeepCopyInto(&out.DataOperationStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupStatus.
func (in *GameBackupStatus) DeepCopy() *GameBackupStatus {
	if in == nil {
		return nil
	}
	out := new(GameBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroy) DeepCopyInto(out *GameDestroy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroy.
func (in *GameDestroy) DeepCopy() *GameDestroy {
	if in == nil {
		return nil
	}
	out := new(GameDestroy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameDestroy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyClaimDeletion) DeepCopyInto(out *GameDestroyClaimDeletion) {
	*out = *in
	in.ClaimRef.DeepCopyInto(&out.ClaimRef)
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	if in.ObservedDeletedAt != nil {
		in, out := &in.ObservedDeletedAt, &out.ObservedDeletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyClaimDeletion.
func (in *GameDestroyClaimDeletion) DeepCopy() *GameDestroyClaimDeletion {
	if in == nil {
		return nil
	}
	out := new(GameDestroyClaimDeletion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyList) DeepCopyInto(out *GameDestroyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameDestroy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyList.
func (in *GameDestroyList) DeepCopy() *GameDestroyList {
	if in == nil {
		return nil
	}
	out := new(GameDestroyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameDestroyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyPreview) DeepCopyInto(out *GameDestroyPreview) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyPreview.
func (in *GameDestroyPreview) DeepCopy() *GameDestroyPreview {
	if in == nil {
		return nil
	}
	out := new(GameDestroyPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroySpec) DeepCopyInto(out *GameDestroySpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.BackupRef != nil {
		in, out := &in.BackupRef, &out.BackupRef
		*out = new(ExactLocalReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySecretRef != nil {
		in, out := &in.RepositorySecretRef, &out.RepositorySecretRef
		*out = new(ExactSecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroySpec.
func (in *GameDestroySpec) DeepCopy() *GameDestroySpec {
	if in == nil {
		return nil
	}
	out := new(GameDestroySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyStatus) DeepCopyInto(out *GameDestroyStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Preview != nil {
		in, out := &in.Preview, &out.Preview
		*out = new(GameDestroyPreview)
		(*in).DeepCopyInto(*out)
	}
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(GameDestroyVerification)
		(*in).DeepCopyInto(*out)
	}
	if in.DeletionJournal != nil {
		in, out := &in.DeletionJournal, &out.DeletionJournal
		*out = make([]GameDestroyClaimDeletion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyStatus.
func (in *GameDestroyStatus) DeepCopy() *GameDestroyStatus {
	if in == nil {
		return nil
	}
	out := new(GameDestroyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyTarget) DeepCopyInto(out *GameDestroyTarget) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyTarget.
func (in *GameDestroyTarget) DeepCopy() *GameDestroyTarget {
	if in == nil {
		return nil
	}
	out := new(GameDestroyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameDestroyVerification) DeepCopyInto(out *GameDestroyVerification) {
	*out = *in
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	in.RepositorySecretRef.DeepCopyInto(&out.RepositorySecretRef)
	in.VerifiedAt.DeepCopyInto(&out.VerifiedAt)
	in.ColdAt.DeepCopyInto(&out.ColdAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameDestroyVerification.
func (in *GameDestroyVerification) DeepCopy() *GameDestroyVerification {
	if in == nil {
		return nil
	}
	out := new(GameDestroyVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestore) DeepCopyInto(out *GameRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestore.
func (in *GameRestore) DeepCopy() *GameRestore {
	if in == nil {
		return nil
	}
	out := new(GameRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreList) DeepCopyInto(out *GameRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreList.
func (in *GameRestoreList) DeepCopy() *GameRestoreList {
	if in == nil {
		return nil
	}
	out := new(GameRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreSpec) DeepCopyInto(out *GameRestoreSpec) {
	*out = *in
	in.DataOperationRequest.DeepCopyInto(&out.DataOperationRequest)
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	in.Target.DeepCopyInto(&out.Target)
	if in.TargetData != nil {
		in, out := &in.TargetData, &out.TargetData
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreSpec.
func (in *GameRestoreSpec) DeepCopy() *GameRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(GameRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreStatus) DeepCopyInto(out *GameRestoreStatus) {
	*out = *in
	in.DataOperationStatus.DeepCopyInto(&out.DataOperationStatus)
	if in.PreflightVerifiedAt != nil {
		in, out := &in.PreflightVerifiedAt, &out.PreflightVerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.RuntimeJournal != nil {
		in, out := &in.RuntimeJournal, &out.RuntimeJournal
		*out = new(RestoreRuntimeJournal)
		**out = **in
	}
	if in.ActivationStartedAt != nil {
		in, out := &in.ActivationStartedAt, &out.ActivationStartedAt
		*out = (*in).DeepCopy()
	}
	if in.CandidateVerification != nil {
		in, out := &in.CandidateVerification, &out.CandidateVerification
		*out = new(CandidateDataVerification)
		(*in).DeepCopyInto(*out)
	}
	if in.CandidateData != nil {
		in, out := &in.CandidateData, &out.CandidateData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveData != nil {
		in, out := &in.ActiveData, &out.ActiveData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreviousData != nil {
		in, out := &in.PreviousData, &out.PreviousData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreStatus.
func (in *GameRestoreStatus) DeepCopy() *GameRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(GameRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServer) DeepCopyInto(out *GameServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServer.
func (in *GameServer) DeepCopy() *GameServer {
	if in == nil {
		return nil
	}
	out := new(GameServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerList) DeepCopyInto(out *GameServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerList.
func (in *GameServerList) DeepCopy() *GameServerList {
	if in == nil {
		return nil
	}
	out := new(GameServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerSpec) DeepCopyInto(out *GameServerSpec) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerSpec.
func (in *GameServerSpec) DeepCopy() *GameServerSpec {
	if in == nil {
		return nil
	}
	out := new(GameServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerStatus) DeepCopyInto(out *GameServerStatus) {
	*out = *in
	if in.ActiveData != nil {
		in, out := &in.ActiveData, &out.ActiveData
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedData != nil {
		in, out := &in.ObservedData, &out.ObservedData
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]ObservedEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerStatus.
func (in *GameServerStatus) DeepCopy() *GameServerStatus {
	if in == nil {
		return nil
	}
	out := new(GameServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineCredentials) DeepCopyInto(out *InlineCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineCredentials.
func (in *InlineCredentials) DeepCopy() *InlineCredentials {
	if in == nil {
		return nil
	}
	out := new(InlineCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedEndpoint) DeepCopyInto(out *ObservedEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedEndpoint.
func (in *ObservedEndpoint) DeepCopy() *ObservedEndpoint {
	if in == nil {
		return nil
	}
	out := new(ObservedEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationAdmission) DeepCopyInto(out *OperationAdmission) {
	*out = *in
	in.AdmittedAt.DeepCopyInto(&out.AdmittedAt)
	in.CredentialExpiresAt.DeepCopyInto(&out.CredentialExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationAdmission.
func (in *OperationAdmission) DeepCopy() *OperationAdmission {
	if in == nil {
		return nil
	}
	out := new(OperationAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationBackupInput) DeepCopyInto(out *OperationBackupInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationBackupInput.
func (in *OperationBackupInput) DeepCopy() *OperationBackupInput {
	if in == nil {
		return nil
	}
	out := new(OperationBackupInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationChildReference) DeepCopyInto(out *OperationChildReference) {
	*out = *in
	in.ExactLocalReference.DeepCopyInto(&out.ExactLocalReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationChildReference.
func (in *OperationChildReference) DeepCopy() *OperationChildReference {
	if in == nil {
		return nil
	}
	out := new(OperationChildReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationConfigureInput) DeepCopyInto(out *OperationConfigureInput) {
	*out = *in
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = new(ComputeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SettingsJSON != nil {
		in, out := &in.SettingsJSON, &out.SettingsJSON
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationConfigureInput.
func (in *OperationConfigureInput) DeepCopy() *OperationConfigureInput {
	if in == nil {
		return nil
	}
	out := new(OperationConfigureInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationCreateInput) DeepCopyInto(out *OperationCreateInput) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.RetainedWorld != nil {
		in, out := &in.RetainedWorld, &out.RetainedWorld
		*out = new(OperationRetainedWorldSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationCreateInput.
func (in *OperationCreateInput) DeepCopy() *OperationCreateInput {
	if in == nil {
		return nil
	}
	out := new(OperationCreateInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationDestroyCommand) DeepCopyInto(out *OperationDestroyCommand) {
	*out = *in
	in.ParentOperationRef.DeepCopyInto(&out.ParentOperationRef)
	in.DestroyRef.DeepCopyInto(&out.DestroyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationDestroyCommand.
func (in *OperationDestroyCommand) DeepCopy() *OperationDestroyCommand {
	if in == nil {
		return nil
	}
	out := new(OperationDestroyCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationDestroyInput) DeepCopyInto(out *OperationDestroyInput) {
	*out = *in
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	if in.RetainedWorld != nil {
		in, out := &in.RetainedWorld, &out.RetainedWorld
		*out = new(OperationRetainedWorldSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationDestroyInput.
func (in *OperationDestroyInput) DeepCopy() *OperationDestroyInput {
	if in == nil {
		return nil
	}
	out := new(OperationDestroyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationFailure) DeepCopyInto(out *OperationFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationFailure.
func (in *OperationFailure) DeepCopy() *OperationFailure {
	if in == nil {
		return nil
	}
	out := new(OperationFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationImageInput) DeepCopyInto(out *OperationImageInput) {
	*out = *in
	in.Resolution.DeepCopyInto(&out.Resolution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationImageInput.
func (in *OperationImageInput) DeepCopy() *OperationImageInput {
	if in == nil {
		return nil
	}
	out := new(OperationImageInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationImageResolution) DeepCopyInto(out *OperationImageResolution) {
	*out = *in
	in.ResolvedAt.DeepCopyInto(&out.ResolvedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationImageResolution.
func (in *OperationImageResolution) DeepCopy() *OperationImageResolution {
	if in == nil {
		return nil
	}
	out := new(OperationImageResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationPlan) DeepCopyInto(out *OperationPlan) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ExactGameServerReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerIntent != nil {
		in, out := &in.ServerIntent, &out.ServerIntent
		*out = new(OperationServerIntent)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySecretRef != nil {
		in, out := &in.RepositorySecretRef, &out.RepositorySecretRef
		*out = new(ExactSecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupRef != nil {
		in, out := &in.BackupRef, &out.BackupRef
		*out = new(ExactLocalReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DestroyRef != nil {
		in, out := &in.DestroyRef, &out.DestroyRef
		*out = new(ExactLocalReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationPlan.
func (in *OperationPlan) DeepCopy() *OperationPlan {
	if in == nil {
		return nil
	}
	out := new(OperationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRequest) DeepCopyInto(out *OperationRequest) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(ExactGameServerReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(OperationCreateInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Configure != nil {
		in, out := &in.Configure, &out.Configure
		*out = new(OperationConfigureInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(OperationImageInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(OperationBackupInput)
		**out = **in
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(OperationRestoreInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Destroy != nil {
		in, out := &in.Destroy, &out.Destroy
		*out = new(OperationDestroyInput)
		(*in).DeepCopyInto(*out)
	}
	if in.DestroyCommand != nil {
		in, out := &in.DestroyCommand, &out.DestroyCommand
		*out = new(OperationDestroyCommand)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRequest.
func (in *OperationRequest) DeepCopy() *OperationRequest {
	if in == nil {
		return nil
	}
	out := new(OperationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRestoreInput) DeepCopyInto(out *OperationRestoreInput) {
	*out = *in
	in.BackupRef.DeepCopyInto(&out.BackupRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRestoreInput.
func (in *OperationRestoreInput) DeepCopy() *OperationRestoreInput {
	if in == nil {
		return nil
	}
	out := new(OperationRestoreInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRetainedWorld) DeepCopyInto(out *OperationRetainedWorld) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRetainedWorld.
func (in *OperationRetainedWorld) DeepCopy() *OperationRetainedWorld {
	if in == nil {
		return nil
	}
	out := new(OperationRetainedWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRetainedWorldSelector) DeepCopyInto(out *OperationRetainedWorldSelector) {
	*out = *in
	in.DecommissionOperationRef.DeepCopyInto(&out.DecommissionOperationRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRetainedWorldSelector.
func (in *OperationRetainedWorldSelector) DeepCopy() *OperationRetainedWorldSelector {
	if in == nil {
		return nil
	}
	out := new(OperationRetainedWorldSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationServerIntent) DeepCopyInto(out *OperationServerIntent) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationServerIntent.
func (in *OperationServerIntent) DeepCopy() *OperationServerIntent {
	if in == nil {
		return nil
	}
	out := new(OperationServerIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationServerTransition) DeepCopyInto(out *OperationServerTransition) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationServerTransition.
func (in *OperationServerTransition) DeepCopy() *OperationServerTransition {
	if in == nil {
		return nil
	}
	out := new(OperationServerTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRuntimeJournal) DeepCopyInto(out *RestoreRuntimeJournal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRuntimeJournal.
func (in *RestoreRuntimeJournal) DeepCopy() *RestoreRuntimeJournal {
	if in == nil {
		return nil
	}
	out := new(RestoreRuntimeJournal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetainedDataClaimReference) DeepCopyInto(out *RetainedDataClaimReference) {
	*out = *in
	in.ClaimRef.DeepCopyInto(&out.ClaimRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetainedDataClaimReference.
func (in *RetainedDataClaimReference) DeepCopy() *RetainedDataClaimReference {
	if in == nil {
		return nil
	}
	out := new(RetainedDataClaimReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetainedDataReference) DeepCopyInto(out *RetainedDataReference) {
	*out = *in
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]RetainedDataClaimReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetainedDataReference.
func (in *RetainedDataReference) DeepCopy() *RetainedDataReference {
	if in == nil {
		return nil
	}
	out := new(RetainedDataReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeDisposition) DeepCopyInto(out *RuntimeDisposition) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeDisposition.
func (in *RuntimeDisposition) DeepCopy() *RuntimeDisposition {
	if in == nil {
		return nil
	}
	out := new(RuntimeDisposition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Reattach != nil {
		in, out := &in.Reattach, &out.Reattach
		*out = new(RetainedDataReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
