//go:build !ignore_autogenerated

// Copyright 2026 gobha-me
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactProvenance) DeepCopyInto(out *ArtifactProvenance) {
	*out = *in
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	in.RepositorySecretRef.DeepCopyInto(&out.RepositorySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactProvenance.
func (in *ArtifactProvenance) DeepCopy() *ArtifactProvenance {
	if in == nil {
		return nil
	}
	out := new(ArtifactProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactVerification) DeepCopyInto(out *ArtifactVerification) {
	*out = *in
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactVerification.
func (in *ArtifactVerification) DeepCopy() *ArtifactVerification {
	if in == nil {
		return nil
	}
	out := new(ArtifactVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupArtifact) DeepCopyInto(out *BackupArtifact) {
	*out = *in
	in.Provenance.DeepCopyInto(&out.Provenance)
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	in.Verification.DeepCopyInto(&out.Verification)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupArtifact.
func (in *BackupArtifact) DeepCopy() *BackupArtifact {
	if in == nil {
		return nil
	}
	out := new(BackupArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CandidateDataVerification) DeepCopyInto(out *CandidateDataVerification) {
	*out = *in
	in.VerifiedAt.DeepCopyInto(&out.VerifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CandidateDataVerification.
func (in *CandidateDataVerification) DeepCopy() *CandidateDataVerification {
	if in == nil {
		return nil
	}
	out := new(CandidateDataVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdDataFence) DeepCopyInto(out *ColdDataFence) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	in.EstablishedAt.DeepCopyInto(&out.EstablishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdDataFence.
func (in *ColdDataFence) DeepCopy() *ColdDataFence {
	if in == nil {
		return nil
	}
	out := new(ColdDataFence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSpec) DeepCopyInto(out *ComputeSpec) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSpec.
func (in *ComputeSpec) DeepCopy() *ComputeSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataOperationRequest) DeepCopyInto(out *DataOperationRequest) {
	*out = *in
	if in.InlineCredentials != nil {
		in, out := &in.InlineCredentials, &out.InlineCredentials
		*out = new(InlineCredentials)
		**out = **in
	}
	in.RepositorySecretRef.DeepCopyInto(&out.RepositorySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataOperationRequest.
func (in *DataOperationRequest) DeepCopy() *DataOperationRequest {
	if in == nil {
		return nil
	}
	out := new(DataOperationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataOperationStatus) DeepCopyInto(out *DataOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(DataSourceSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Fence != nil {
		in, out := &in.Fence, &out.Fence
		*out = new(ColdDataFence)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(BackupArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeDisposition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataOperationStatus.
func (in *DataOperationStatus) DeepCopy() *DataOperationStatus {
	if in == nil {
		return nil
	}
	out := new(DataOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPathIdentity) DeepCopyInto(out *DataPathIdentity) {
	*out = *in
	in.ClaimRef.DeepCopyInto(&out.ClaimRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPathIdentity.
func (in *DataPathIdentity) DeepCopy() *DataPathIdentity {
	if in == nil {
		return nil
	}
	out := new(DataPathIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSnapshot) DeepCopyInto(out *DataSourceSnapshot) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSnapshot.
func (in *DataSourceSnapshot) DeepCopy() *DataSourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(DataSourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactGameServerReference) DeepCopyInto(out *ExactGameServerReference) {
	*out = *in
	in.ExactLocalReference.DeepCopyInto(&out.ExactLocalReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactGameServerReference.
func (in *ExactGameServerReference) DeepCopy() *ExactGameServerReference {
	if in == nil {
		return nil
	}
	out := new(ExactGameServerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactLocalReference) DeepCopyInto(out *ExactLocalReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactLocalReference.
func (in *ExactLocalReference) DeepCopy() *ExactLocalReference {
	if in == nil {
		return nil
	}
	out := new(ExactLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExactSecretReference) DeepCopyInto(out *ExactSecretReference) {
	*out = *in
	in.ExactLocalReference.DeepCopyInto(&out.ExactLocalReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExactSecretReference.
func (in *ExactSecretReference) DeepCopy() *ExactSecretReference {
	if in == nil {
		return nil
	}
	out := new(ExactSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackup) DeepCopyInto(out *GameBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackup.
func (in *GameBackup) DeepCopy() *GameBackup {
	if in == nil {
		return nil
	}
	out := new(GameBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupList) DeepCopyInto(out *GameBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupList.
func (in *GameBackupList) DeepCopy() *GameBackupList {
	if in == nil {
		return nil
	}
	out := new(GameBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupSpec) DeepCopyInto(out *GameBackupSpec) {
	*out = *in
	in.DataOperationRequest.DeepCopyInto(&out.DataOperationRequest)
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupSpec.
func (in *GameBackupSpec) DeepCopy() *GameBackupSpec {
	if in == nil {
		return nil
	}
	out := new(GameBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameBackupStatus) DeepCopyInto(out *GameBackupStatus) {
	*out = *in
	in.DataOperationStatus.DeepCopyInto(&out.DataOperationStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameBackupStatus.
func (in *GameBackupStatus) DeepCopy() *GameBackupStatus {
	if in == nil {
		return nil
	}
	out := new(GameBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestore) DeepCopyInto(out *GameRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestore.
func (in *GameRestore) DeepCopy() *GameRestore {
	if in == nil {
		return nil
	}
	out := new(GameRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreList) DeepCopyInto(out *GameRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreList.
func (in *GameRestoreList) DeepCopy() *GameRestoreList {
	if in == nil {
		return nil
	}
	out := new(GameRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreSpec) DeepCopyInto(out *GameRestoreSpec) {
	*out = *in
	in.DataOperationRequest.DeepCopyInto(&out.DataOperationRequest)
	in.BackupRef.DeepCopyInto(&out.BackupRef)
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreSpec.
func (in *GameRestoreSpec) DeepCopy() *GameRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(GameRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameRestoreStatus) DeepCopyInto(out *GameRestoreStatus) {
	*out = *in
	in.DataOperationStatus.DeepCopyInto(&out.DataOperationStatus)
	if in.ActivationStartedAt != nil {
		in, out := &in.ActivationStartedAt, &out.ActivationStartedAt
		*out = (*in).DeepCopy()
	}
	if in.CandidateVerification != nil {
		in, out := &in.CandidateVerification, &out.CandidateVerification
		*out = new(CandidateDataVerification)
		(*in).DeepCopyInto(*out)
	}
	if in.CandidateData != nil {
		in, out := &in.CandidateData, &out.CandidateData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveData != nil {
		in, out := &in.ActiveData, &out.ActiveData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreviousData != nil {
		in, out := &in.PreviousData, &out.PreviousData
		*out = make([]DataPathIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameRestoreStatus.
func (in *GameRestoreStatus) DeepCopy() *GameRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(GameRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServer) DeepCopyInto(out *GameServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServer.
func (in *GameServer) DeepCopy() *GameServer {
	if in == nil {
		return nil
	}
	out := new(GameServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerList) DeepCopyInto(out *GameServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GameServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerList.
func (in *GameServerList) DeepCopy() *GameServerList {
	if in == nil {
		return nil
	}
	out := new(GameServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GameServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerSpec) DeepCopyInto(out *GameServerSpec) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerSpec.
func (in *GameServerSpec) DeepCopy() *GameServerSpec {
	if in == nil {
		return nil
	}
	out := new(GameServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerStatus) DeepCopyInto(out *GameServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]ObservedEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerStatus.
func (in *GameServerStatus) DeepCopy() *GameServerStatus {
	if in == nil {
		return nil
	}
	out := new(GameServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineCredentials) DeepCopyInto(out *InlineCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineCredentials.
func (in *InlineCredentials) DeepCopy() *InlineCredentials {
	if in == nil {
		return nil
	}
	out := new(InlineCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedEndpoint) DeepCopyInto(out *ObservedEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedEndpoint.
func (in *ObservedEndpoint) DeepCopy() *ObservedEndpoint {
	if in == nil {
		return nil
	}
	out := new(ObservedEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeDisposition) DeepCopyInto(out *RuntimeDisposition) {
	*out = *in
	in.GameServer.DeepCopyInto(&out.GameServer)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeDisposition.
func (in *RuntimeDisposition) DeepCopy() *RuntimeDisposition {
	if in == nil {
		return nil
	}
	out := new(RuntimeDisposition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
