---
apiVersion: v1
kind: Service
metadata:
  name: arcadectl-api
  namespace: arcadectl-system
  labels:
    app.kubernetes.io/name: arcadectl-api
    app.kubernetes.io/part-of: arcadectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arcadectl-api
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
